# Generated by Django 5.1.1 on 2024-10-09 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_remove_project_unique_project_per_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='urgency',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=6),
        ),
    ]
