# Generated by Django 5.1.1 on 2024-10-09 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_project_urgency'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='completed',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
