# Generated by Django 5.1.1 on 2024-10-10 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_project_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='description_show',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
