# Generated by Django 5.1.1 on 2024-10-26 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_project_bucket_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='bucket_name',
            new_name='bucket',
        ),
    ]
